---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1
  name: svc-php73
spec:
  ports:
  - name: php73
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: app1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1
  name: svc-nginx
spec:
  ports:
  - name: nginx-http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-https
    port: 443
    protocol: TCP
    targetPort: 443 
  selector:
    app: app1
  type: NodePort
