---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-cm
  namespace: dc01-production
data:
  MYSQL_USER: wordpress
  MYSQL_DATABASE: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-cm
  namespace: dc01-production
data:
  WORDPRESS_DB_HOST: 'mariadb-svc'
  WORDPRESS_DB_USER: 'wordpress'
  WORDPRESS_DB_NAME: 'wordpress'
