---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: dc01-production
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: dc01-production
  labels:
    app: wordpress
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
